// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk6ieSG8YY8vZzJb85eq8186nMlMIkq0I',
    appId: '1:187928956063:web:d552bb5d6cab27949b26aa',
    messagingSenderId: '187928956063',
    projectId: 'wufcare-a3704',
    authDomain: 'wufcare-a3704.firebaseapp.com',
    databaseURL: 'https://wufcare-a3704-default-rtdb.firebaseio.com',
    storageBucket: 'wufcare-a3704.firebasestorage.app',
    measurementId: 'G-4QCEMN1FMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2SfHoMXQmrCqpNHZOlkjsiFHsdhNizRc',
    appId: '1:187928956063:android:84541b6cd92b0f389b26aa',
    messagingSenderId: '187928956063',
    projectId: 'wufcare-a3704',
    databaseURL: 'https://wufcare-a3704-default-rtdb.firebaseio.com',
    storageBucket: 'wufcare-a3704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMYy4u4u97KHGKv-Oc8Npgv47ZTmkyofU',
    appId: '1:187928956063:ios:dba06b0afb2c374d9b26aa',
    messagingSenderId: '187928956063',
    projectId: 'wufcare-a3704',
    databaseURL: 'https://wufcare-a3704-default-rtdb.firebaseio.com',
    storageBucket: 'wufcare-a3704.firebasestorage.app',
    iosBundleId: 'com.example.wufcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMYy4u4u97KHGKv-Oc8Npgv47ZTmkyofU',
    appId: '1:187928956063:ios:dba06b0afb2c374d9b26aa',
    messagingSenderId: '187928956063',
    projectId: 'wufcare-a3704',
    databaseURL: 'https://wufcare-a3704-default-rtdb.firebaseio.com',
    storageBucket: 'wufcare-a3704.firebasestorage.app',
    iosBundleId: 'com.example.wufcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk6ieSG8YY8vZzJb85eq8186nMlMIkq0I',
    appId: '1:187928956063:web:b2a0764eaacf0aba9b26aa',
    messagingSenderId: '187928956063',
    projectId: 'wufcare-a3704',
    authDomain: 'wufcare-a3704.firebaseapp.com',
    databaseURL: 'https://wufcare-a3704-default-rtdb.firebaseio.com',
    storageBucket: 'wufcare-a3704.firebasestorage.app',
    measurementId: 'G-29EWH70NGW',
  );
}
